<a href="https://colab.research.google.com/github/skku-kdj/MLRobustness_eval/blob/main/learning_pytorch/Pytorch_base.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Wed Nov  8 04:28:38 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0].shape

torch.Size([2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

why random tensor?

DNN이 랜덤 텐서로 시작해서 데이터를 받으며 이 랜덤값을 개선함. 이 과정이 데이터를 더 잘 표현하기 위한 방법

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[1.6672e-01, 4.4990e-01, 6.3074e-01, 8.8584e-01],
        [1.5956e-01, 7.8392e-04, 7.4367e-01, 9.7603e-01],
        [6.1856e-01, 8.4674e-01, 5.7862e-01, 9.8978e-01]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
 ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Big 3 errors with running PyTorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [ ]:
float_32_tensor = torch.tensor([3, 6, 9],
                               dtype = torch.float32,
                               device = None,
                               requires_grad = False)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype, float_32_tensor.dtype

(torch.float16, torch.float32)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype = torch.int64)

In [ ]:
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.5461, 0.6438, 0.2768, 0.5258],
        [0.6357, 0.5607, 0.6551, 0.6905],
        [0.9657, 0.6665, 0.9744, 0.8062]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor * 10, tensor - 10, tensor / 10

(tensor([11, 12, 13]),
 tensor([10, 20, 30]),
 tensor([-9, -8, -7]),
 tensor([0.1000, 0.2000, 0.3000]))

In [ ]:
tensor * tensor, torch.matmul(tensor, tensor)#dot product

(tensor([1, 4, 9]), tensor(14))

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.18 ms, sys: 0 ns, total: 1.18 ms
Wall time: 1.23 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 26 µs, sys: 4 µs, total: 30 µs
Wall time: 33.6 µs


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

torch.matmul(tensor_A, tensor_B.T), torch.matmul(tensor_A.T, tensor_B)

(tensor([[ 23,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]),
 tensor([[ 89,  98],
         [116, 128]]))

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min(), x.max()

(tensor(0), tensor(90))

In [ ]:
x.mean()

RuntimeError: ignored

In [ ]:
x.type(torch.float32).mean(), torch.sum(x)

(tensor(45.), tensor(450))

In [ ]:
#find position of minimum value in tensor
x.argmin()

tensor(0)

In [ ]:
#find position of maximum value in tensor
x.argmax()

tensor(9)

In [ ]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
#share memory
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
z = z + 1
z, x

(tensor([[ 6.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked, x_stacked.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([4, 10]))

In [ ]:
#squeeze: remove single dimentions of target tensor
x_reshaped.shape, x_reshaped.squeeze().shape, x_reshaped.squeeze()

(torch.Size([10, 1]),
 torch.Size([10]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
#unsqueeze: add a single dimention to a target tensor
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_squeezed, x_unsqueezed, x_squeezed.shape, x_unsqueezed.shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 5.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10]),
 torch.Size([10, 1]))

In [ ]:
#permute: rearrange the dimensions of target tensor in a specific order
x_original = torch.rand(size=(224, 224, 3))

#permute - get color goes to 0 dimension
x_permuted = x_original.permute(2, 0, 1)#shifts axis 0->1, 1->2, 2->0

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
x_original[0, 0, 0] = 121
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(121.), tensor(121.))

###indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0, 0, 0], x[0, 1, 0], x[0, 2, 0], x[:, :, 0]

(tensor(1), tensor(4), tensor(7), tensor([[1, 4, 7]]))

In [ ]:
x[0, 0], x[0 ,0, :]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducbility: trying to take random out of random

to reduce randomness in Pytorch, concept of random seed is needed


In [ ]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.9395, 0.5948, 0.1140, 0.5058],
         [0.2770, 0.1125, 0.1895, 0.0815],
         [0.5582, 0.5436, 0.9246, 0.7542]]),
 tensor([[0.7248, 0.2064, 0.4114, 0.1378],
         [0.4560, 0.2129, 0.7759, 0.9239],
         [0.8232, 0.6954, 0.9616, 0.6057]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [ ]:
#random but reporducible tensors
RANDOM_SEED = 1214

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D, random_tensor_C == random_tensor_D

(tensor([[0.0382, 0.1491, 0.0342, 0.2427],
         [0.0387, 0.9063, 0.8370, 0.2479],
         [0.8696, 0.5650, 0.7197, 0.2651]]),
 tensor([[0.0382, 0.1491, 0.0342, 0.2427],
         [0.0387, 0.9063, 0.8370, 0.2479],
         [0.8696, 0.5650, 0.7197, 0.2651]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [ ]:
#check GPU access with Pytorch
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1, 2, 3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
#putting tensors(and models) on the GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#moving tensors back to CPU(numpy only works on CPU)
tensors_on_gpu.numpy()

NameError: ignored

In [ ]:
#again, moving tensor back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu, tensor_on_gpu, tensor_back_on_cpu.numpy()

(tensor([1, 2, 3]), tensor([1, 2, 3], device='cuda:0'), array([1, 2, 3]))