<a href="https://colab.research.google.com/github/skku-kdj/MLRobustness_eval/blob/main/learning_pytorch/pytorch_base.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Tue Feb 27 11:17:02 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[0].shape

torch.Size([2])

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

why random tensor?

DNN이 랜덤 텐서로 시작해서 데이터를 받으며 이 랜덤값을 개선함. 이 과정이 데이터를 더 잘 표현하기 위한 방법

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0378, 0.8745, 0.8184, 0.8661],
        [0.0168, 0.2050, 0.4504, 0.1841],
        [0.1627, 0.0385, 0.6705, 0.1657]])

In [17]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
 ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

In [21]:
one_to_ten = torch.arange(1, 11)
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Big 3 errors with running PyTorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [23]:
float_32_tensor = torch.tensor([3, 6, 9],
                               dtype = torch.float32,
                               device = None,
                               requires_grad = False)

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype, float_32_tensor.dtype

(torch.float16, torch.float32)

In [25]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype = torch.int64)

In [26]:
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[4.1778e-01, 4.0900e-02, 3.5244e-01, 8.2704e-01],
        [4.2120e-01, 3.3591e-01, 6.0642e-01, 6.0660e-01],
        [6.5154e-04, 4.1690e-01, 7.6601e-01, 4.2465e-01]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [27]:
tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor * 10, tensor - 10, tensor / 10

(tensor([11, 12, 13]),
 tensor([10, 20, 30]),
 tensor([-9, -8, -7]),
 tensor([0.1000, 0.2000, 0.3000]))

In [28]:
tensor * tensor, torch.matmul(tensor, tensor)#dot product

(tensor([1, 4, 9]), tensor(14))

In [29]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.27 ms, sys: 44 µs, total: 1.31 ms
Wall time: 4.22 ms


In [30]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 31 µs, sys: 0 ns, total: 31 µs
Wall time: 33.9 µs


tensor(14)

In [31]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

torch.matmul(tensor_A, tensor_B.T), torch.matmul(tensor_A.T, tensor_B)

(tensor([[ 23,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]),
 tensor([[ 89,  98],
         [116, 128]]))

In [32]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
x.min(), x.max()

(tensor(0), tensor(90))

In [36]:
x.type(torch.float32).mean(), torch.sum(x)

(tensor(45.), tensor(450))

In [37]:
#find position of minimum value in tensor
x.argmin()

tensor(0)

In [38]:
#find position of maximum value in tensor
x.argmax()

tensor(9)

In [39]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [40]:
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [41]:
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [42]:
#share memory
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [43]:
z = z + 1
z, x

(tensor([[ 6.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [44]:
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked, x_stacked.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([4, 10]))

In [45]:
#squeeze: remove single dimentions of target tensor
x_reshaped.shape, x_reshaped.squeeze().shape, x_reshaped.squeeze()

(torch.Size([10, 1]),
 torch.Size([10]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [46]:
#unsqueeze: add a single dimention to a target tensor
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_squeezed, x_unsqueezed, x_squeezed.shape, x_unsqueezed.shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 5.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10]),
 torch.Size([10, 1]))

In [47]:
#permute: rearrange the dimensions of target tensor in a specific order
x_original = torch.rand(size=(224, 224, 3))

#permute - get color goes to 0 dimension
x_permuted = x_original.permute(2, 0, 1)#shifts axis 0->1, 1->2, 2->0

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [48]:
x_original[0, 0, 0] = 121
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(121.), tensor(121.))

###indexing

In [49]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
x[0, 0, 0], x[0, 1, 0], x[0, 2, 0], x[:, :, 0]

(tensor(1), tensor(4), tensor(7), tensor([[1, 4, 7]]))

In [51]:
x[0, 0], x[0 ,0, :]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [52]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [53]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [54]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducbility: trying to take random out of random

to reduce randomness in Pytorch, concept of random seed is needed


In [55]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.1174, 0.9784, 0.7859, 0.1278],
         [0.4079, 0.1358, 0.6431, 0.5427],
         [0.9126, 0.4399, 0.2623, 0.7353]]),
 tensor([[0.4197, 0.6189, 0.4554, 0.6481],
         [0.3673, 0.0514, 0.9238, 0.0351],
         [0.6630, 0.5368, 0.0978, 0.4663]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [56]:
#random but reporducible tensors
RANDOM_SEED = 1214

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D, random_tensor_C == random_tensor_D

(tensor([[0.0382, 0.1491, 0.0342, 0.2427],
         [0.0387, 0.9063, 0.8370, 0.2479],
         [0.8696, 0.5650, 0.7197, 0.2651]]),
 tensor([[0.0382, 0.1491, 0.0342, 0.2427],
         [0.0387, 0.9063, 0.8370, 0.2479],
         [0.8696, 0.5650, 0.7197, 0.2651]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [57]:
#check GPU access with Pytorch
torch.cuda.is_available()

True

In [58]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [59]:
torch.cuda.device_count()

1

In [60]:
tensor = torch.tensor([1, 2, 3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [61]:
#putting tensors(and models) on the GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [63]:
#moving tensors back to CPU(numpy only works on CPU)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [64]:
#again, moving tensor back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu, tensor_on_gpu, tensor_back_on_cpu.numpy()

(tensor([1, 2, 3]), tensor([1, 2, 3], device='cuda:0'), array([1, 2, 3]))